# Generated by Django 3.2.1 on 2022-06-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('store', models.ManyToManyField(to='app_goods.Store')),
            ],
        ),
    ]
