# Generated by Django 3.2.1 on 2022-06-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='store',
            field=models.ManyToManyField(related_name='eng', to='app_goods.Store'),
        ),
    ]
