# Generated by Django 3.2.1 on 2022-06-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_alter_good_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='pop',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='GoodBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.good')),
            ],
        ),
    ]
